/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './app/__root'
import { Route as LoginImport } from './app/login'
import { Route as AuthenticatedImport } from './app/_authenticated'
import { Route as IndexImport } from './app/index'
import { Route as AuthenticatedFriendsImport } from './app/_authenticated/friends'
import { Route as AuthenticatedFriendRequestsImport } from './app/_authenticated/friend-requests'
import { Route as AuthenticatedSettingsRouteImport } from './app/_authenticated/_settings/route'
import { Route as AuthenticatedChatsRouteImport } from './app/_authenticated/_chats/route'
import { Route as AuthenticatedSettingsSettingsImport } from './app/_authenticated/_settings/settings'
import { Route as AuthenticatedChatsChatsImport } from './app/_authenticated/_chats/chats'
import { Route as AuthenticatedSettingsSettingsIndexImport } from './app/_authenticated/_settings/settings.index'
import { Route as AuthenticatedChatsChatsIndexImport } from './app/_authenticated/_chats/chats.index'
import { Route as AuthenticatedChatsChatsIdImport } from './app/_authenticated/_chats/chats.$id'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedFriendsRoute = AuthenticatedFriendsImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedFriendRequestsRoute =
  AuthenticatedFriendRequestsImport.update({
    id: '/friend-requests',
    path: '/friend-requests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedSettingsRouteRoute = AuthenticatedSettingsRouteImport.update(
  {
    id: '/_settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const AuthenticatedChatsRouteRoute = AuthenticatedChatsRouteImport.update({
  id: '/_chats',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedSettingsSettingsRoute =
  AuthenticatedSettingsSettingsImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedChatsChatsRoute = AuthenticatedChatsChatsImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AuthenticatedChatsRouteRoute,
} as any)

const AuthenticatedSettingsSettingsIndexRoute =
  AuthenticatedSettingsSettingsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsSettingsRoute,
  } as any)

const AuthenticatedChatsChatsIndexRoute =
  AuthenticatedChatsChatsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedChatsChatsRoute,
  } as any)

const AuthenticatedChatsChatsIdRoute = AuthenticatedChatsChatsIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedChatsChatsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_chats': {
      id: '/_authenticated/_chats'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedChatsRouteImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/_settings': {
      id: '/_authenticated/_settings'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/friend-requests': {
      id: '/_authenticated/friend-requests'
      path: '/friend-requests'
      fullPath: '/friend-requests'
      preLoaderRoute: typeof AuthenticatedFriendRequestsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/friends': {
      id: '/_authenticated/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthenticatedFriendsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/_chats/chats': {
      id: '/_authenticated/_chats/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsChatsImport
      parentRoute: typeof AuthenticatedChatsRouteImport
    }
    '/_authenticated/_settings/settings': {
      id: '/_authenticated/_settings/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsSettingsImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/_chats/chats/$id': {
      id: '/_authenticated/_chats/chats/$id'
      path: '/$id'
      fullPath: '/chats/$id'
      preLoaderRoute: typeof AuthenticatedChatsChatsIdImport
      parentRoute: typeof AuthenticatedChatsChatsImport
    }
    '/_authenticated/_chats/chats/': {
      id: '/_authenticated/_chats/chats/'
      path: '/'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsChatsIndexImport
      parentRoute: typeof AuthenticatedChatsChatsImport
    }
    '/_authenticated/_settings/settings/': {
      id: '/_authenticated/_settings/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsSettingsIndexImport
      parentRoute: typeof AuthenticatedSettingsSettingsImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedChatsChatsRouteChildren {
  AuthenticatedChatsChatsIdRoute: typeof AuthenticatedChatsChatsIdRoute
  AuthenticatedChatsChatsIndexRoute: typeof AuthenticatedChatsChatsIndexRoute
}

const AuthenticatedChatsChatsRouteChildren: AuthenticatedChatsChatsRouteChildren =
  {
    AuthenticatedChatsChatsIdRoute: AuthenticatedChatsChatsIdRoute,
    AuthenticatedChatsChatsIndexRoute: AuthenticatedChatsChatsIndexRoute,
  }

const AuthenticatedChatsChatsRouteWithChildren =
  AuthenticatedChatsChatsRoute._addFileChildren(
    AuthenticatedChatsChatsRouteChildren,
  )

interface AuthenticatedChatsRouteRouteChildren {
  AuthenticatedChatsChatsRoute: typeof AuthenticatedChatsChatsRouteWithChildren
}

const AuthenticatedChatsRouteRouteChildren: AuthenticatedChatsRouteRouteChildren =
  {
    AuthenticatedChatsChatsRoute: AuthenticatedChatsChatsRouteWithChildren,
  }

const AuthenticatedChatsRouteRouteWithChildren =
  AuthenticatedChatsRouteRoute._addFileChildren(
    AuthenticatedChatsRouteRouteChildren,
  )

interface AuthenticatedSettingsSettingsRouteChildren {
  AuthenticatedSettingsSettingsIndexRoute: typeof AuthenticatedSettingsSettingsIndexRoute
}

const AuthenticatedSettingsSettingsRouteChildren: AuthenticatedSettingsSettingsRouteChildren =
  {
    AuthenticatedSettingsSettingsIndexRoute:
      AuthenticatedSettingsSettingsIndexRoute,
  }

const AuthenticatedSettingsSettingsRouteWithChildren =
  AuthenticatedSettingsSettingsRoute._addFileChildren(
    AuthenticatedSettingsSettingsRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsSettingsRoute: typeof AuthenticatedSettingsSettingsRouteWithChildren
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsSettingsRoute:
      AuthenticatedSettingsSettingsRouteWithChildren,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedChatsRouteRoute: typeof AuthenticatedChatsRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedFriendRequestsRoute: typeof AuthenticatedFriendRequestsRoute
  AuthenticatedFriendsRoute: typeof AuthenticatedFriendsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChatsRouteRoute: AuthenticatedChatsRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedFriendRequestsRoute: AuthenticatedFriendRequestsRoute,
  AuthenticatedFriendsRoute: AuthenticatedFriendsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/friend-requests': typeof AuthenticatedFriendRequestsRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/chats': typeof AuthenticatedChatsChatsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsSettingsRouteWithChildren
  '/chats/$id': typeof AuthenticatedChatsChatsIdRoute
  '/chats/': typeof AuthenticatedChatsChatsIndexRoute
  '/settings/': typeof AuthenticatedSettingsSettingsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/friend-requests': typeof AuthenticatedFriendRequestsRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/chats/$id': typeof AuthenticatedChatsChatsIdRoute
  '/chats': typeof AuthenticatedChatsChatsIndexRoute
  '/settings': typeof AuthenticatedSettingsSettingsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/_chats': typeof AuthenticatedChatsRouteRouteWithChildren
  '/_authenticated/_settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/friend-requests': typeof AuthenticatedFriendRequestsRoute
  '/_authenticated/friends': typeof AuthenticatedFriendsRoute
  '/_authenticated/_chats/chats': typeof AuthenticatedChatsChatsRouteWithChildren
  '/_authenticated/_settings/settings': typeof AuthenticatedSettingsSettingsRouteWithChildren
  '/_authenticated/_chats/chats/$id': typeof AuthenticatedChatsChatsIdRoute
  '/_authenticated/_chats/chats/': typeof AuthenticatedChatsChatsIndexRoute
  '/_authenticated/_settings/settings/': typeof AuthenticatedSettingsSettingsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/friend-requests'
    | '/friends'
    | '/chats'
    | '/settings'
    | '/chats/$id'
    | '/chats/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/friend-requests'
    | '/friends'
    | '/chats/$id'
    | '/chats'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/_chats'
    | '/_authenticated/_settings'
    | '/_authenticated/friend-requests'
    | '/_authenticated/friends'
    | '/_authenticated/_chats/chats'
    | '/_authenticated/_settings/settings'
    | '/_authenticated/_chats/chats/$id'
    | '/_authenticated/_chats/chats/'
    | '/_authenticated/_settings/settings/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/_chats",
        "/_authenticated/_settings",
        "/_authenticated/friend-requests",
        "/_authenticated/friends"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_authenticated/_chats": {
      "filePath": "_authenticated/_chats/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/_chats/chats"
      ]
    },
    "/_authenticated/_settings": {
      "filePath": "_authenticated/_settings/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/_settings/settings"
      ]
    },
    "/_authenticated/friend-requests": {
      "filePath": "_authenticated/friend-requests.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/friends": {
      "filePath": "_authenticated/friends.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/_chats/chats": {
      "filePath": "_authenticated/_chats/chats.tsx",
      "parent": "/_authenticated/_chats",
      "children": [
        "/_authenticated/_chats/chats/$id",
        "/_authenticated/_chats/chats/"
      ]
    },
    "/_authenticated/_settings/settings": {
      "filePath": "_authenticated/_settings/settings.tsx",
      "parent": "/_authenticated/_settings",
      "children": [
        "/_authenticated/_settings/settings/"
      ]
    },
    "/_authenticated/_chats/chats/$id": {
      "filePath": "_authenticated/_chats/chats.$id.tsx",
      "parent": "/_authenticated/_chats/chats"
    },
    "/_authenticated/_chats/chats/": {
      "filePath": "_authenticated/_chats/chats.index.tsx",
      "parent": "/_authenticated/_chats/chats"
    },
    "/_authenticated/_settings/settings/": {
      "filePath": "_authenticated/_settings/settings.index.tsx",
      "parent": "/_authenticated/_settings/settings"
    }
  }
}
ROUTE_MANIFEST_END */
