/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as RegisterRouteImport } from './app/register'
import { Route as OtpRouteImport } from './app/otp'
import { Route as LoginRouteImport } from './app/login'
import { Route as AuthenticatedRouteRouteImport } from './app/_authenticated/route'
import { Route as IndexRouteImport } from './app/index'
import { Route as AuthenticatedFriendRequestsRouteRouteImport } from './app/_authenticated/friend-requests/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './app/_authenticated/_settings/route'
import { Route as AuthenticatedFriendsRouteRouteImport } from './app/_authenticated/_friends/route'
import { Route as AuthenticatedChatsRouteRouteImport } from './app/_authenticated/_chats/route'
import { Route as AuthenticatedSettingsSettingsRouteImport } from './app/_authenticated/_settings/settings'
import { Route as AuthenticatedFriendsFriendsRouteImport } from './app/_authenticated/_friends/friends'
import { Route as AuthenticatedChatsChatsRouteImport } from './app/_authenticated/_chats/chats'
import { Route as AuthenticatedSettingsSettingsIndexRouteImport } from './app/_authenticated/_settings/settings.index'
import { Route as AuthenticatedFriendsFriendsIndexRouteImport } from './app/_authenticated/_friends/friends.index'
import { Route as AuthenticatedChatsChatsIndexRouteImport } from './app/_authenticated/_chats/chats.index'
import { Route as AuthenticatedChatsChatsIdRouteImport } from './app/_authenticated/_chats/chats.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFriendRequestsRouteRoute =
  AuthenticatedFriendRequestsRouteRouteImport.update({
    id: '/friend-requests',
    path: '/friend-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/_settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFriendsRouteRoute =
  AuthenticatedFriendsRouteRouteImport.update({
    id: '/_friends',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsRouteRoute = AuthenticatedChatsRouteRouteImport.update({
  id: '/_chats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsSettingsRoute =
  AuthenticatedSettingsSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedFriendsFriendsRoute =
  AuthenticatedFriendsFriendsRouteImport.update({
    id: '/friends',
    path: '/friends',
    getParentRoute: () => AuthenticatedFriendsRouteRoute,
  } as any)
const AuthenticatedChatsChatsRoute = AuthenticatedChatsChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AuthenticatedChatsRouteRoute,
} as any)
const AuthenticatedSettingsSettingsIndexRoute =
  AuthenticatedSettingsSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsSettingsRoute,
  } as any)
const AuthenticatedFriendsFriendsIndexRoute =
  AuthenticatedFriendsFriendsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFriendsFriendsRoute,
  } as any)
const AuthenticatedChatsChatsIndexRoute =
  AuthenticatedChatsChatsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedChatsChatsRoute,
  } as any)
const AuthenticatedChatsChatsIdRoute =
  AuthenticatedChatsChatsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedChatsChatsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/register': typeof RegisterRoute
  '/friend-requests': typeof AuthenticatedFriendRequestsRouteRoute
  '/chats': typeof AuthenticatedChatsChatsRouteWithChildren
  '/friends': typeof AuthenticatedFriendsFriendsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsSettingsRouteWithChildren
  '/chats/$id': typeof AuthenticatedChatsChatsIdRoute
  '/chats/': typeof AuthenticatedChatsChatsIndexRoute
  '/friends/': typeof AuthenticatedFriendsFriendsIndexRoute
  '/settings/': typeof AuthenticatedSettingsSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/register': typeof RegisterRoute
  '/friend-requests': typeof AuthenticatedFriendRequestsRouteRoute
  '/chats/$id': typeof AuthenticatedChatsChatsIdRoute
  '/chats': typeof AuthenticatedChatsChatsIndexRoute
  '/friends': typeof AuthenticatedFriendsFriendsIndexRoute
  '/settings': typeof AuthenticatedSettingsSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/register': typeof RegisterRoute
  '/_authenticated/_chats': typeof AuthenticatedChatsRouteRouteWithChildren
  '/_authenticated/_friends': typeof AuthenticatedFriendsRouteRouteWithChildren
  '/_authenticated/_settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/friend-requests': typeof AuthenticatedFriendRequestsRouteRoute
  '/_authenticated/_chats/chats': typeof AuthenticatedChatsChatsRouteWithChildren
  '/_authenticated/_friends/friends': typeof AuthenticatedFriendsFriendsRouteWithChildren
  '/_authenticated/_settings/settings': typeof AuthenticatedSettingsSettingsRouteWithChildren
  '/_authenticated/_chats/chats/$id': typeof AuthenticatedChatsChatsIdRoute
  '/_authenticated/_chats/chats/': typeof AuthenticatedChatsChatsIndexRoute
  '/_authenticated/_friends/friends/': typeof AuthenticatedFriendsFriendsIndexRoute
  '/_authenticated/_settings/settings/': typeof AuthenticatedSettingsSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/otp'
    | '/register'
    | '/friend-requests'
    | '/chats'
    | '/friends'
    | '/settings'
    | '/chats/$id'
    | '/chats/'
    | '/friends/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/otp'
    | '/register'
    | '/friend-requests'
    | '/chats/$id'
    | '/chats'
    | '/friends'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/otp'
    | '/register'
    | '/_authenticated/_chats'
    | '/_authenticated/_friends'
    | '/_authenticated/_settings'
    | '/_authenticated/friend-requests'
    | '/_authenticated/_chats/chats'
    | '/_authenticated/_friends/friends'
    | '/_authenticated/_settings/settings'
    | '/_authenticated/_chats/chats/$id'
    | '/_authenticated/_chats/chats/'
    | '/_authenticated/_friends/friends/'
    | '/_authenticated/_settings/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  OtpRoute: typeof OtpRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/friend-requests': {
      id: '/_authenticated/friend-requests'
      path: '/friend-requests'
      fullPath: '/friend-requests'
      preLoaderRoute: typeof AuthenticatedFriendRequestsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_settings': {
      id: '/_authenticated/_settings'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_friends': {
      id: '/_authenticated/_friends'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedFriendsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_chats': {
      id: '/_authenticated/_chats'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedChatsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_settings/settings': {
      id: '/_authenticated/_settings/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsSettingsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/_friends/friends': {
      id: '/_authenticated/_friends/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthenticatedFriendsFriendsRouteImport
      parentRoute: typeof AuthenticatedFriendsRouteRoute
    }
    '/_authenticated/_chats/chats': {
      id: '/_authenticated/_chats/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsChatsRouteImport
      parentRoute: typeof AuthenticatedChatsRouteRoute
    }
    '/_authenticated/_settings/settings/': {
      id: '/_authenticated/_settings/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsSettingsRoute
    }
    '/_authenticated/_friends/friends/': {
      id: '/_authenticated/_friends/friends/'
      path: '/'
      fullPath: '/friends/'
      preLoaderRoute: typeof AuthenticatedFriendsFriendsIndexRouteImport
      parentRoute: typeof AuthenticatedFriendsFriendsRoute
    }
    '/_authenticated/_chats/chats/': {
      id: '/_authenticated/_chats/chats/'
      path: '/'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsChatsIndexRouteImport
      parentRoute: typeof AuthenticatedChatsChatsRoute
    }
    '/_authenticated/_chats/chats/$id': {
      id: '/_authenticated/_chats/chats/$id'
      path: '/$id'
      fullPath: '/chats/$id'
      preLoaderRoute: typeof AuthenticatedChatsChatsIdRouteImport
      parentRoute: typeof AuthenticatedChatsChatsRoute
    }
  }
}

interface AuthenticatedChatsChatsRouteChildren {
  AuthenticatedChatsChatsIdRoute: typeof AuthenticatedChatsChatsIdRoute
  AuthenticatedChatsChatsIndexRoute: typeof AuthenticatedChatsChatsIndexRoute
}

const AuthenticatedChatsChatsRouteChildren: AuthenticatedChatsChatsRouteChildren =
  {
    AuthenticatedChatsChatsIdRoute: AuthenticatedChatsChatsIdRoute,
    AuthenticatedChatsChatsIndexRoute: AuthenticatedChatsChatsIndexRoute,
  }

const AuthenticatedChatsChatsRouteWithChildren =
  AuthenticatedChatsChatsRoute._addFileChildren(
    AuthenticatedChatsChatsRouteChildren,
  )

interface AuthenticatedChatsRouteRouteChildren {
  AuthenticatedChatsChatsRoute: typeof AuthenticatedChatsChatsRouteWithChildren
}

const AuthenticatedChatsRouteRouteChildren: AuthenticatedChatsRouteRouteChildren =
  {
    AuthenticatedChatsChatsRoute: AuthenticatedChatsChatsRouteWithChildren,
  }

const AuthenticatedChatsRouteRouteWithChildren =
  AuthenticatedChatsRouteRoute._addFileChildren(
    AuthenticatedChatsRouteRouteChildren,
  )

interface AuthenticatedFriendsFriendsRouteChildren {
  AuthenticatedFriendsFriendsIndexRoute: typeof AuthenticatedFriendsFriendsIndexRoute
}

const AuthenticatedFriendsFriendsRouteChildren: AuthenticatedFriendsFriendsRouteChildren =
  {
    AuthenticatedFriendsFriendsIndexRoute:
      AuthenticatedFriendsFriendsIndexRoute,
  }

const AuthenticatedFriendsFriendsRouteWithChildren =
  AuthenticatedFriendsFriendsRoute._addFileChildren(
    AuthenticatedFriendsFriendsRouteChildren,
  )

interface AuthenticatedFriendsRouteRouteChildren {
  AuthenticatedFriendsFriendsRoute: typeof AuthenticatedFriendsFriendsRouteWithChildren
}

const AuthenticatedFriendsRouteRouteChildren: AuthenticatedFriendsRouteRouteChildren =
  {
    AuthenticatedFriendsFriendsRoute:
      AuthenticatedFriendsFriendsRouteWithChildren,
  }

const AuthenticatedFriendsRouteRouteWithChildren =
  AuthenticatedFriendsRouteRoute._addFileChildren(
    AuthenticatedFriendsRouteRouteChildren,
  )

interface AuthenticatedSettingsSettingsRouteChildren {
  AuthenticatedSettingsSettingsIndexRoute: typeof AuthenticatedSettingsSettingsIndexRoute
}

const AuthenticatedSettingsSettingsRouteChildren: AuthenticatedSettingsSettingsRouteChildren =
  {
    AuthenticatedSettingsSettingsIndexRoute:
      AuthenticatedSettingsSettingsIndexRoute,
  }

const AuthenticatedSettingsSettingsRouteWithChildren =
  AuthenticatedSettingsSettingsRoute._addFileChildren(
    AuthenticatedSettingsSettingsRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsSettingsRoute: typeof AuthenticatedSettingsSettingsRouteWithChildren
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsSettingsRoute:
      AuthenticatedSettingsSettingsRouteWithChildren,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatsRouteRoute: typeof AuthenticatedChatsRouteRouteWithChildren
  AuthenticatedFriendsRouteRoute: typeof AuthenticatedFriendsRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedFriendRequestsRouteRoute: typeof AuthenticatedFriendRequestsRouteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatsRouteRoute: AuthenticatedChatsRouteRouteWithChildren,
  AuthenticatedFriendsRouteRoute: AuthenticatedFriendsRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedFriendRequestsRouteRoute: AuthenticatedFriendRequestsRouteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  OtpRoute: OtpRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
